apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak-db
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.serviceAccount.azureClientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: keycloak-db-username
          objectType: secret
        - |
          objectName: keycloak-db-password
          objectType: secret
        - |
          objectName: keycloak-admin-username
          objectType: secret
        - |
          objectName: keycloak-admin-password
          objectType: secret
  secretObjects:
    - secretName: keycloak-db-credentials
      type: Opaque
      data:
        - objectName: keycloak-db-username
          key: username
        - objectName: keycloak-db-password
          key: password
    - secretName: keycloak-admin-credentials
      type: Opaque
      data:
        - objectName: keycloak-admin-username
          key: username
        - objectName: keycloak-admin-password
          key: password
