apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-api-config
  namespace: {{ .Values.namespace }}
data:
  KEYCLOAK_ISSUER: {{ .Values.config.keycloakIssuerURL | quote }}
  KEYCLOAK_JWKS_URL: {{ .Values.config.keycloakJWKSURL | quote }}
  KEY_VAULT_URL: {{ .Values.keyVault.url | quote }}
  NATS_URL: {{ .Values.config.natsURL | quote }}
  POOL_TTL: {{ .Values.config.poolTTL | quote }}
  POOL_MAX_CONNS: {{ .Values.config.poolMaxConns | quote }}
  JWKS_CACHE_TTL: {{ .Values.config.jwksCacheTTL | quote }}
