apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: {{ .Values.namespace }}
  labels:
    app: rest-api
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: rest-api
          image: "{{ .Values.image.repository }}/nats-auth-middleware:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: rest-api-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: rest-api
