apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rest-api-allow-hug
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: rest-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: haproxy-unified-gateway
      ports:
        - port: 8080
